import { timeAgo } from '../lib/format.js';

function ThemeToggle({ dark, onToggle }) {
  return (
    <button
      type="button"
      onClick={onToggle}
      aria-label={dark ? 'Switch to light theme' : 'Switch to dark theme'}
      className="rounded-lg p-2 text-ink-500 transition-colors hover:bg-ink-100 hover:text-ink-900 dark:text-ink-400 dark:hover:bg-ink-800 dark:hover:text-ink-100"
    >
      {dark ? (
        <svg viewBox="0 0 20 20" aria-hidden="true" className="h-4.5 w-4.5">
          <circle cx="10" cy="10" r="3.6" fill="currentColor" />
          <path
            d="M10 1.6v2M10 16.4v2M1.6 10h2M16.4 10h2M4.1 4.1l1.4 1.4M14.5 14.5l1.4 1.4M15.9 4.1l-1.4 1.4M5.5 14.5l-1.4 1.4"
            stroke="currentColor"
            strokeWidth="1.6"
            strokeLinecap="round"
          />
        </svg>
      ) : (
        <svg viewBox="0 0 20 20" aria-hidden="true" className="h-4.5 w-4.5">
          <path
            d="M17 12.3A7.4 7.4 0 0 1 7.7 3a7.4 7.4 0 1 0 9.3 9.3Z"
            fill="currentColor"
          />
        </svg>
      )}
    </button>
  );
}

export default function Header({ meta, dark, onToggleTheme, onRefresh, refreshing }) {
  return (
    <header className="sticky top-0 z-20 border-b border-ink-200/80 bg-ink-50/85 backdrop-blur-md dark:border-ink-800/80 dark:bg-ink-950/85">
      <div className="mx-auto flex max-w-3xl items-center gap-3 px-4 py-3">
        <div className="min-w-0 flex-1">
          <h1 className="flex items-baseline gap-2 text-base font-semibold tracking-tight text-ink-900 dark:text-ink-50">
            Touchline
            <span className="hidden text-xs font-normal text-ink-500 sm:inline dark:text-ink-400">
              football news, minus the padding
            </span>
          </h1>

          <p className="mt-0.5 flex items-center gap-1.5 text-[11px] text-ink-400 dark:text-ink-500">
            {meta?.lastUpdated ? (
              <>
                <span
                  className={`h-1.5 w-1.5 rounded-full ${
                    meta.lastError ? 'bg-amber-500' : 'bg-pitch-500'
                  }`}
                  aria-hidden="true"
                />
                updated {timeAgo(meta.lastUpdated)}
                <span aria-hidden="true">·</span>
                {meta.storyCount} stories
                <span aria-hidden="true">·</span>
                <span title={`Summaries generated by the ${meta.engine} engine`}>
                  {meta.engine === 'claude' ? 'Claude' : 'local'} summaries
                </span>
              </>
            ) : (
              <span>gathering stories…</span>
            )}
          </p>
        </div>

        <button
          type="button"
          onClick={onRefresh}
          disabled={refreshing}
          aria-label="Refresh stories"
          className="rounded-lg p-2 text-ink-500 transition-colors hover:bg-ink-100 hover:text-ink-900 disabled:opacity-50 dark:text-ink-400 dark:hover:bg-ink-800 dark:hover:text-ink-100"
        >
          <svg
            viewBox="0 0 20 20"
            aria-hidden="true"
            className={`h-4.5 w-4.5 ${refreshing ? 'animate-spin' : ''}`}
          >
            <path
              d="M16.5 10a6.5 6.5 0 1 1-1.9-4.6M16.5 2.5V6H13"
              fill="none"
              stroke="currentColor"
              strokeWidth="1.6"
              strokeLinecap="round"
              strokeLinejoin="round"
            />
          </svg>
        </button>

        <ThemeToggle dark={dark} onToggle={onToggleTheme} />
      </div>
    </header>
  );
}
